
import React from 'react';

const AddIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg 
        width="16" 
        height="16" 
        viewBox="0 0 24 24" 
        fill="none" 
        stroke="currentColor" 
        strokeWidth="3" 
        strokeLinecap="round" 
        strokeLinejoin="round" 
        className="text-white"
        {...props}
    >
        <line x1="12" y1="5" x2="12" y2="19"></line>
        <line x1="5" y1="12" x2="19" y2="12"></line>
    </svg>
);


interface ImageCardProps {
  src: string;
  index: number;
  onView: (src: string) => void;
  onAddToPrompt: (src: string) => void;
}

const ImageCard: React.FC<ImageCardProps> = ({ src, index, onView, onAddToPrompt }) => {
  const handleAddToPrompt = (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent triggering onView when clicking the button
    onAddToPrompt(src);
  };

  return (
    <div
      className="relative group w-full aspect-[3/4] bg-[#2d2f31] rounded-2xl overflow-hidden animate-fadeInScaleUp cursor-pointer"
      style={{ animationDelay: `${index * 100}ms`, opacity: 0 }}
      onClick={() => onView(src)}
    >
      <img
        src={src}
        alt="Generated by AI"
        className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
      />
      <button
        onClick={handleAddToPrompt}
        className="absolute bottom-3 right-3 w-8 h-8 flex items-center justify-center bg-black/40 backdrop-blur-sm rounded-full opacity-0 group-hover:opacity-100 transition-all duration-200 hover:bg-black/60"
        aria-label="Add image to prompt"
      >
        <AddIcon />
      </button>
    </div>
  );
};

export default ImageCard;
