import React from 'react';
import { PlayIcon } from './icons/PlayIcon';

interface ImageCardProps {
  src: string;
  showPlayButton?: boolean;
  index: number;
  onSelect: (src: string) => void;
}

const ImageCard: React.FC<ImageCardProps> = ({ src, showPlayButton, index, onSelect }) => {
  return (
    <div
      className="relative group w-full aspect-[3/4] bg-[#2d2f31] rounded-2xl overflow-hidden animate-fadeInScaleUp cursor-pointer"
      style={{ animationDelay: `${index * 100}ms`, opacity: 0 }}
      onClick={() => onSelect(src)}
    >
      <img
        src={src}
        alt="Generated by AI"
        className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
      />
      {showPlayButton && (
        <div className="absolute bottom-3 right-3 w-8 h-8 flex items-center justify-center bg-black/40 backdrop-blur-sm rounded-full opacity-0 group-hover:opacity-100 transition-opacity">
          <PlayIcon />
        </div>
      )}
    </div>
  );
};

export default ImageCard;